/**
 *
 *  api_v1_ArticleController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
using namespace drogon;

namespace api::v1 {
/**
 * @brief this class is created by the drogon_ctl command (drogon_ctl create controller -r
 * api::v1::ArticleController). this class is a restful API controller.
 */
class ArticleController : public drogon::HttpController<ArticleController> {
  public:
    METHOD_LIST_BEGIN
    // use METHOD_ADD to add your custom processing function here;
    METHOD_ADD(ArticleController::getOne, "/{1}", Get, Options);
    METHOD_ADD(ArticleController::get, "", Get, Options);
    METHOD_ADD(ArticleController::create, "", Post, Options);
    METHOD_ADD(ArticleController::updateOne, "/{1}", Put, Options);
    // METHOD_ADD(ArticleController::update,"",Put,Options);
    METHOD_ADD(ArticleController::deleteOne, "/{1}", Delete, Options);
    METHOD_LIST_END

    void getOne(const HttpRequestPtr &req, std::function<void(const HttpResponsePtr &)> &&callback,
                std::string &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback, std::string &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback, std::string &&id);
    void get(const HttpRequestPtr &req, std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req, std::function<void(const HttpResponsePtr &)> &&callback);

    //    void update(const HttpRequestPtr &req,
    //                std::function<void(const HttpResponsePtr &)> &&callback);
};
} // namespace api::v1
