/**
 *
 *  api_v1_Articles.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "api_v1_Articles.h"

#include "Articlesdto.h"

#include <string>

using namespace api::v1;

void Articles::getOne(const HttpRequestPtr &req,
                      std::function<void(const HttpResponsePtr &)> &&callback, std::string &&id) {}

void Articles::get(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback) {}
void Articles::create(const HttpRequestPtr &req,
                      std::function<void(const HttpResponsePtr &)> &&callback) {
    auto body = req->body();
    try {
        auto j = nlohmann::json::parse(body);
        auto dto = j.get<yblog::dto::CreateArticle>();
    } catch (const std::exception &e) {
        LOG_WARN << e.what();
    }
    auto db = drogon::app().getDbClient();
    // db->execSqlAsync("")
}
void Articles::updateOne(const HttpRequestPtr &req,
                         std::function<void(const HttpResponsePtr &)> &&callback,
                         std::string &&id) {}

/*
void Articles::update(const HttpRequestPtr &req,
                      std::function<void(const HttpResponsePtr &)> &&callback)
{

}*/

void Articles::deleteOne(const HttpRequestPtr &req,
                         std::function<void(const HttpResponsePtr &)> &&callback,
                         std::string &&id) {}
