/**
 *
 *  api_v1_ArticleController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "api_v1_ArticleController.h"
#include <string>

using namespace api::v1;

void ArticleController::getOne(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback,
                               std::string &&id)
{
}

void ArticleController::get(const HttpRequestPtr &req,
                            std::function<void(const HttpResponsePtr &)> &&callback)
{
}
void ArticleController::create(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback)
{
}
void ArticleController::updateOne(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback,
                                  std::string &&id)
{
}

/*
void ArticleController::update(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback)
{

}*/

void ArticleController::deleteOne(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback,
                                  std::string &&id)
{
}
