/**
 *
 *  api_v1_Articles.h
 *  This file is generated by drogon_ctl
 *  command:drogon_ctl create controller -r api::v1::Articles
 */

#pragma once

#include <drogon/HttpController.h>
using namespace drogon;

namespace api::v1 {
/**
 * @brief this class is created by the drogon_ctl command (drogon_ctl create controller -r
 * api::v1::Articles). this class is a restful API controller.
 */
class Articles : public drogon::HttpController<Articles> {
  public:
    METHOD_LIST_BEGIN
    // use METHOD_ADD to add your custom processing function here;
    METHOD_ADD(Articles::getOne, "/{1}", Get, Options);
    METHOD_ADD(Articles::get, "", Get, Options);
    METHOD_ADD(Articles::create, "", Post, Options);
    METHOD_ADD(Articles::updateOne, "/{1}", Put, Options);
    // METHOD_ADD(Articles::update,"",Put,Options);
    METHOD_ADD(Articles::deleteOne, "/{1}", Delete, Options);
    METHOD_LIST_END

    void getOne(const HttpRequestPtr &req, std::function<void(const HttpResponsePtr &)> &&callback,
                std::string &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback, std::string &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback, std::string &&id);
    void get(const HttpRequestPtr &req, std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req, std::function<void(const HttpResponsePtr &)> &&callback);

    //    void update(const HttpRequestPtr &req,
    //                std::function<void(const HttpResponsePtr &)> &&callback);
};
} // namespace api::v1
